name: HYPERGROAI_ASSIGNMENT

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: HYPERGROAI_DB

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
